language: python
python:
  - "3.7.3"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install -y python-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev ffmpeg=7:3.2.14-1
  - pip3 install av==6.1.2
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
