language: python
python:
  - "3.7.3"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev ffmpeg
install:
  - pip3 install av
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
