- id: '1536623212578'
  alias: Notify that the day ahead is hot
  initial_state: true
  trigger:
  - at: 07:00:00
    platform: time
  condition:
  - above: '23'
    condition: numeric_state
    entity_id: sensor.dark_sky_daytime_high_temperature_0
  action:
  - data:
      message: Check the air con hose is properly fitted
      title: It's gonna be a hot one
    service: notify.notify
- id: '1537046653369'
  alias: Turn off bed after 45 minutes
  initial_state: true
  trigger:
  - entity_id: switch.bed
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:45:00
  - data:
      entity_id: switch.bed
    service: switch.turn_off
- id: '1544469969774'
  alias: CPU Temp alert
  initial_state: true
  trigger:
  - platform: template
    value_template: '{{ states.sensor.cpu_temp.state | int > 90.0 }}'
  action:
  - data:
      message: CPU has reached 90 degrees
      title: CPU Temperature Alert
    service: notify.notify
  - data:
      message: CPU has reached 90 degrees
      title: CPU Temperature Alert
    service: persistent_notification.create
- id: '1545569969564'
  alias: Disk Space Alert
  initial_state: true
  trigger:
  - platform: template
    value_template: '{{ states.sensor.disk_use_percent_.state | int > 90.0 }}'
  action:
  - data:
      message: Disk usage has reached 90%
      title: Disk Usage Alert
    service: notify.notify
  - data:
      message: Disk usage has reached 90%
      title: Disk Usage Alert
    service: persistent_notification.create
- id: '1555511372666'
  alias: USG CPU above threshold for 5 minutes
  initial_state: true
  trigger:
  - above: '90'
    entity_id: sensor.unifi_gateway_wan_cpu
    for: 00:05:00
    platform: numeric_state
  condition: []
  action:
  - data:
      message: USG CPU usage above 90%
      title: USG CPU Alert
    service: notify.notify
  - data:
      message: USG CPU usage above 90%
      title: USG CPU Alert
    service: persistent_notification.create
- id: '1558654178327'
  alias: AC on at 24
  trigger:
  - above: '24'
    entity_id: sensor.average_indoor_temp
    for: 00:05:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: device_tracker.oneplus_6t
    state: home
  - condition: state
    entity_id: switch.aircon
    state: 'off'
  action:
  - data:
      entity_id: switch.aircon
    service: switch.turn_on
  initial_state: true
- id: '1558654263292'
  alias: AC Off at 23
  trigger:
  - below: '23'
    entity_id: sensor.average_indoor_temp
    for: 00:05:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: device_tracker.oneplus_6t
    state: home
  - condition: state
    entity_id: switch.aircon
    state: 'on'
  action:
  - data:
      entity_id: switch.aircon
    service: switch.turn_off
  initial_state: true
