#- id: '1536621541441'
#  alias: Tom leaves home
#  trigger:
#  - entity_id: device_tracker.oneplus_6t
#    from: home
#    platform: state
#    to: not_home
#  condition:
#  - condition: state
#    entity_id: device_tracker.hannahs_iphone
#    state: not_home
#  action:
#  - alias: ''
#    data: {}
#    service: shell_command.foscam_turn_on_start_motion
#  - data:
#      entity_id: climate.living_room
#      preset_mode: eco
#    service: climate.set_preset_mode
#  - data:
#      away_mode: away
#    service: nest.set_away_mode
#  - data:
#      entity_id: group.all_lights
#    service: light.turn_off
#  initial_state: true
#- id: '1536622222448'
#  alias: Tom arrives home
#  trigger:
#  - entity_id: device_tracker.oneplus_6t
#    from: not_home
#    platform: state
#    to: home
#  condition:
#  - condition: state
#    entity_id: device_tracker.hannahs_iphone
#    state: not_home
#  action:
#  - service: shell_command.foscam_turn_off_stop_motion
#  - data:
#      entity_id: climate.living_room
#      preset_mode: 'null'
#    service: climate.set_preset_mode
#  - data:
#      away_mode: home
#    service: nest.set_away_mode
#  initial_state: true
#- id: '1536622518656'
#  alias: Motion alarm
#  trigger:
#  - entity_id: binary_sensor.hall_motion
#    from: 'off'
#    platform: state
#    to: 'on'
#  condition:
#  - condition: state
#    entity_id: device_tracker.oneplus_6t
#    state: not_home
#  - condition: state
#    entity_id: device_tracker.hannahs_iphone
#    state: not_home
#  action:
#  - data:
#      data:
#        priority: high
#      message: Motion detected in hallway, no-one home
#      title: Motion Detected
#    service: notify.html5_oneplus6t
#  - data:
#      message: Motion detected in hallway, no-one home
#      title: Motion Detected
#    service: persistent_notification.create
#  - data:
#      data:
#        type: tts
#      message: You are on camera and I have notified the owner. Please leave now.
#      target:
#      - media_player.thomas_s_2nd_echo
#      - media_player.living_room
#      - media_player.bedroom
#    service: notify.alexa_media
#  - delay: 00:00:10
#  - data:
#      data:
#        type: tts
#      message: You are on camera and I have notified the owner. Please leave now.
#      target:
#      - media_player.thomas_s_2nd_echo
#      - media_player.living_room
#      - media_player.bedroom
#    service: notify.alexa_media
#  initial_state: true
- id: '1536623212578'
  alias: Notify that the day ahead is hot
  initial_state: true
  trigger:
  - at: 07:00:00
    platform: time
  condition:
  - above: '23'
    condition: numeric_state
    entity_id: sensor.dark_sky_daytime_high_temperature_0
  action:
  - data:
      message: Check the air con hose is properly fitted
      title: It's gonna be a hot one
    service: notify.notify
#- id: '1536623844065'
#  alias: PS4 Netflix Open
#  initial_state: true
#  trigger:
#  - entity_id: sensor.current_ps4_app
#    platform: state
#    to: Netflix
#  condition:
#  - after: sunset
#    before: sunrise
#    condition: sun
#  action:
#  - alias: ''
#    data:
#      entity_id: scene.livingroom_dim
#    service: scene.turn_on
#- id: '1536623905398'
#  alias: PS4 Netflix Closed
#  initial_state: true
#  trigger:
#  - entity_id: sensor.current_ps4_app
#    from: Netflix
#    platform: state
#  condition:
#  - after: sunset
#    before: sunrise
#    condition: sun
#  action:
#  - data:
#      entity_id: scene.livingroom_normal
#    service: scene.turn_on
- id: '1537046653369'
  alias: Turn off bed after 45 minutes
  initial_state: true
  trigger:
  - entity_id: switch.bed
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:45:00
  - data:
      entity_id: switch.bed
    service: switch.turn_off
#- id: '1539025813455'
#  alias: Turn off TV if PS4 turns off
#  initial_state: true
#  trigger:
#  - entity_id: media_player.playstation_4
#    platform: state
#    to: 'off'
#  condition: []
#  action:
#  - data:
#      entity_id: media_player.tv
#    service: media_player.turn_off
#- id: '1544468069774'
#  alias: PS4 Plex Stopped/Paused UP2
#  initial_state: true
#  trigger:
#  - entity_id: media_player.ezqtfvhzz76nc2s81mxkjkh3
#    from: playing
#    platform: state
#    to: paused
#  - entity_id: media_player.ezqtfvhzz76nc2s81mxkjkh3
#    from: playing
#    platform: state
#    to: idle
#  - entity_id: media_player.hpnmo7k8u8ldn1sjbyf8apez
#    from: playing
#    platform: state
#    to: paused
#  - entity_id: media_player.hpnmo7k8u8ldn1sjbyf8apez
#    from: playing
#    platform: state
#    to: idle
#  condition:
#  - condition: state
#    entity_id: sun.sun
#    state: below_horizon
#  action:
#  - data:
#      entity_id: scene.livingroom_normal
#    service: scene.turn_on
#- id: '1544468271787'
#  alias: Plex Playing UP2
#  initial_state: true
#  trigger:
#  - entity_id: media_player.ezqtfvhzz76nc2s81mxkjkh3
#    from: paused
#    platform: state
#    to: playing
#  - entity_id: media_player.ezqtfvhzz76nc2s81mxkjkh3
#    from: idle
#    platform: state
#    to: playing
#  - entity_id: media_player.hpnmo7k8u8ldn1sjbyf8apez
#    from: paused
#    platform: state
#    to: playing
#  - entity_id: media_player.hpnmo7k8u8ldn1sjbyf8apez
#    from: idle
#    platform: state
#    to: playing
#  condition:
#  - condition: state
#    entity_id: sun.sun
#    state: below_horizon
#  action:
#  - data:
#      entity_id: scene.livingroom_dim
#    service: scene.turn_on
- id: '1544469969774'
  alias: CPU Temp alert
  initial_state: true
  trigger:
  - platform: template
    value_template: '{{ states.sensor.cpu_temp.state | int > 90.0 }}'
  action:
  - data:
      message: CPU has reached 90 degrees
      title: CPU Temperature Alert
    service: notify.notify
  - data:
      message: CPU has reached 90 degrees
      title: CPU Temperature Alert
    service: persistent_notification.create
- id: '1545569969564'
  alias: Disk Space Alert
  initial_state: true
  trigger:
  - platform: template
    value_template: '{{ states.sensor.disk_use_percent_.state | int > 90.0 }}'
  action:
  - data:
      message: Disk usage has reached 90%
      title: Disk Usage Alert
    service: notify.notify
  - data:
      message: Disk usage has reached 90%
      title: Disk Usage Alert
    service: persistent_notification.create
#- id: '1546827588933'
#  alias: Network Upgrade Available
#  initial_state: true
#  trigger:
#  - above: '0'
#    entity_id: sensor.unifi_gateway_firmware_upgradable
#    platform: numeric_state
#  condition: []
#  action:
#  - data:
#      message: A UniFi device has an upgrade available
#      title: Upgrade Available
#    service: notify.notify
#- id: '1547567181070'
#  alias: Hannah arrives home
#  trigger:
#  - entity_id: device_tracker.hannahs_iphone
#    from: not_home
#    platform: state
#    to: home
#  condition:
#  - condition: state
#    entity_id: device_tracker.oneplus_6t
#    state: not_home
#  action:
#  - service: shell_command.foscam_turn_off_stop_motion
#  - data:
#      entity_id: climate.living_room
#      preset_mode: 'null'
#    service: climate.set_preset_mode
#  - data:
#      away_mode: home
#    service: nest.set_away_mode
#  initial_state: true
#- id: '1547567259550'
#  alias: Hannah leaves home
#  trigger:
#  - entity_id: device_tracker.hannahs_iphone
#    from: home
#    platform: state
#    to: not_home
#  condition:
#  - condition: state
#    entity_id: device_tracker.oneplus_6t
#    state: not_home
#  action:
#  - service: shell_command.foscam_turn_on_start_motion
#  - data:
#      entity_id: climate.living_room
#      preset_mode: eco
#    service: climate.set_preset_mode
#  - data:
#      away_mode: away
#    service: nest.set_away_mode
#  - data:
#      entity_id: group.all_lights
#    service: light.turn_off
#  initial_state: true
#- id: '1548542027000'
#  alias: Fridge has turned off
#  initial_state: true
#  trigger:
#  - entity_id: switch.fridge
#    from: 'on'
#    platform: state
#    to: 'off'
#  condition: []
#  action:
#  - data:
#      message: Fridge has turned off
#      title: Fridge Alert
#    service: notify.notify
#  - data:
#      message: Fridge has turned off
#      title: Fridge Alert
#    service: persistent_notification.create
#- id: '1548603683301'
#  alias: Freezer has turned off
#  initial_state: true
#  trigger:
#  - entity_id: switch.freezer
#    from: 'on'
#    platform: state
#    to: 'off'
#  condition: []
#  action:
#  - data:
#      message: Freezer has turned off
#      title: Freezer Alert
#    service: notify.notify
#  - data:
#      message: Freezer has turned off
#      title: Freezer Alert
#    service: persistent_notification.create
#- id: '1548892170652'
#  alias: Heat off at night
#  initial_state: true
#  trigger:
#  - at: 00:00:00
#    platform: time
#  condition:
#  - condition: state
#    entity_id: device_tracker.oneplus_6t
#    state: home
#  action:
#  - data:
#      entity_id: climate.living_room
#      temperature: '15'
#    service: climate.set_temperature
#- id: '1548892267947'
#  alias: Heat on at 9am
#  trigger:
#  - at: 09:00:00
#    platform: time
#  condition:
#  - condition: state
#    entity_id: device_tracker.oneplus_6t
#    state: home
#  action:
#  - data:
#      entity_id: climate.living_room
#      temperature: '20'
#    service: climate.set_temperature
#- id: '1551057534839'
#  alias: Update Electricity Usage
#  initial_state: true
#  trigger:
#  - entity_id: sensor.octopus_elec
#    platform: numeric_state
#    above: 47
#  action:
#  - data_template:
#      entity_id: input_number.electricity
#      value: '{{ (state_attr("sensor.octopus_elec", "results") | map(attribute="consumption")|
#        sum ) | round(3) }}'
#    service: input_number.set_value
#- id: '1551057534840'
#  alias: Update Gas Usage
#  initial_state: true
#  trigger:
#  - entity_id: sensor.octopus_gas
#    platform: numeric_state
#    above: 47
#  action:
#  - data_template:
#      entity_id: input_number.gas
#      value: '{{ (state_attr("sensor.octopus_gas", "results") | map(attribute="consumption")|
#        sum ) | round(3) }}'
#    service: input_number.set_value
- id: '1555511372666'
  alias: USG CPU above threshold for 5 minutes
  initial_state: true
  trigger:
  - above: '90'
    entity_id: sensor.unifi_gateway_wan_cpu
    for: 00:05:00
    platform: numeric_state
  condition: []
  action:
  - data:
      message: USG CPU usage above 90%
      title: USG CPU Alert
    service: notify.notify
  - data:
      message: USG CPU usage above 90%
      title: USG CPU Alert
    service: persistent_notification.create
- id: '1558654178327'
  alias: AC on at 24
  trigger:
  - above: '24'
    entity_id: sensor.average_indoor_temp
    for: 00:05:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: device_tracker.oneplus_6t
    state: home
  - condition: state
    entity_id: switch.aircon
    state: 'off'
  action:
  - data:
      entity_id: switch.aircon
    service: switch.turn_on
  initial_state: true
- id: '1558654263292'
  alias: AC Off at 23
  trigger:
  - below: '23'
    entity_id: sensor.average_indoor_temp
    for: 00:05:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: device_tracker.oneplus_6t
    state: home
  - condition: state
    entity_id: switch.aircon
    state: 'on'
  action:
  - data:
      entity_id: switch.aircon
    service: switch.turn_off
  initial_state: true
#- id: '1558868217213'
#  alias: Keep Freezer On
#  initial_state: true
#  trigger:
#  - entity_id: switch.freezer
#    from: 'on'
#    platform: state
#    to: 'off'
#  condition: []
#  action:
#  - data:
#      entity_id: switch.freezer
#    service: switch.turn_on
#- id: '1558872874526'
#  alias: Keep Fridge On
#  initial_state: true
#  trigger:
#  - entity_id: switch.fridge
#    from: 'off'
#    platform: state
#    to: 'on'
#  condition: []
#  action:
#  - data:
#      entity_id: switch.fridge
#    service: switch.turn_on
#- id: '1558987711846'
#  alias: 'Blinds: Close at 10:30pm'
#  trigger:
#  - at: '22:30:00'
#    platform: time
#  condition:
#  - condition: state
#    entity_id: device_tracker.hannahs_iphone
#    state: home
#  action:
#  - data:
#      entity_id: cover.blinds
#    service: cover.close_cover
#  - data:
#      data:
#        actions:
#        - action: stop_blinds
#          icon: mdi:close
#          title: Stop
#        priority: high
#        ttl: 180
#      message: Closing blinds
#      title: Blinds
#    service: notify.notify
#  initial_state: true
#- id: '1558987787319'
#  alias: 'Blinds: Open at sunrise'
#  trigger:
#  - event: sunrise
#    platform: sun
#  condition: []
#  action:
#  - data:
#      entity_id: cover.blinds
#    service: cover.open_cover
#  initial_state: true
#- id: '1561684183414'
#  initial_state: true
#  alias: Night
#  trigger:
#  - event: sunset
#    platform: sun
#  condition: []
#  action:
#  - data:
#      name: dark
#    service: frontend.set_theme
#  - data:
#      entity_id: switch.circadian_lighting
#    service: switch.turn_on
#- id: '1561684230072'
#  alias: Day
#  trigger:
#  - event: sunrise
#    platform: sun
#  condition: []
#  action:
#  - data:
#      name: default
#    service: frontend.set_theme
#  - data:
#      entity_id: switch.circadian_lighting
#    service: switch.turn_off
- id: '1564779035283'
  alias: HomeAssistant Started at Night
  trigger:
  - event: start
    platform: homeassistant
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - data:
      entity_id: automation.night
    service: automation.trigger
- id: '1565994688928'
  alias: 'Circadian Light: AM'
  trigger:
  - event: sunrise
    platform: sun
  condition:
  - condition: state
    entity_id: device_tracker.hannahs_iphone
    state: home
  action:
  - data:
      entity_id: light.bedroom
    service: light.turn_on
#- id: '1567774991908'
#  alias: Doorbell
#  trigger:
#  - platform: mqtt
#    topic: ha/doorbell/notify
#  condition: []
#  action:
#  - data:
#      message: There's somebody at the door
#      notification_id: '888'
#      title: Doorbell
#    service: persistent_notification.create
#  - data:
#      data:
#        actions:
#        - action: dismiss
#          icon: mdi:close
#          title: Dismiss
#        priority: high
#      message: There's somebody at the door
#      title: Doorbell
#    service: notify.notify
#  - data:
#      data:
#        type: tts
#      message: There's somebody at the door.
#      target:
#      - media_player.thomas_s_2nd_echo
#      - media_player.living_room
#      - media_player.bedroom
#    service: notify.alexa_media
#  initial_state: true
#- id: '1567787593804'
#  initial_state: true
#  alias: Dismiss doorbell
#  trigger:
#  - event_data:
#      action: dismiss
#    event_type: html5_notification.clicked
#    platform: event
#  condition: []
#  action:
#  - data:
#      notification_id: '888'
#    service: persistent_notification.dismiss
