- platform: mqtt
  name: "My Computer - Connected"
  state_topic: "iotlink/workgroup/pandora/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1
- platform: ping
  host: !secret switch_address
  name: "Nintendo Switch"
