auth:
alexa_media: !include alexa_media.yaml
automation: !include automations.yaml
breaking_changes:
camera: !include camera.yaml
cast: !include cast.yaml
circadian_lighting:
  min_colortemp: 1500
  max_colortemp: 5000
cover: !include cover.yaml
cloud: !include cloud.yaml
config:
device_tracker: !include device_tracker.yaml
discovery:
frontend: !include themes.yaml
group: !include groups.yaml
hacs: !include hacs.yaml
history: !include history.yaml
homeassistant: !include homeassistant.yaml
http: !include http.yaml
input_number: !include input_number.yaml
logbook:
logger: !include logger.yaml
media_player: !include media_player.yaml
nest: !include nest.yaml
notify: !include notify.yaml
person:
plex: !include plex.yaml
recorder: !include recorder.yaml
scene: !include scene.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
shell_command: !include shell_command.yaml
sun:
switch: !include switch.yaml
system_health:
