auth:
alexa_media: !include alexa_media.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
breaking_changes:
camera: !include camera.yaml
cast: !include cast.yaml
circadian_lighting: !include circadian_lighting.yaml
cover: !include cover.yaml
cloud: !include cloud.yaml
config:
device_tracker: !include device_tracker.yaml
discovery:
frontend: !include frontend.yaml
google: !include google.yaml
group: !include groups.yaml
#hacs: !include hacs.yaml
history: !include history.yaml
homeassistant: !include homeassistant.yaml
http: !include http.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
logbook:
logger: !include logger.yaml
media_player: !include media_player.yaml
mobile_app:
neato: !include neato.yaml
nest: !include nest.yaml
notify: !include notify.yaml
person:
plex: !include plex.yaml
recorder: !include recorder.yaml
remote_homeassistant: !include remote.yaml
scene: !include scene.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
shell_command: !include shell_command.yaml
stream: !include stream.yaml
sun:
switch: !include switch.yaml
system_health:
tplink: !include tplink.yaml
wake_on_lan:
