- platform: group
  name: Living Room
  entities:
    - cover.living_room_1
    - cover.living_room_2
- platform: group
  name: Blinds
  entities:
    - cover.living_room_1
    - cover.living_room_2
    - cover.bedroom1
    - cover.office1
